### ISSUE TITLE
GoogleAppsCardV1DateTimePicker unuse

### ISSUE THREAD

**Issue by diaowenyang** [googleworkspace/hangouts-chat-samples#114]
`{
	"actionResponse": {
		"dialogAction": {
			"dialog": {
				"body": {
					"sections": [
						{
							"widgets": [
								{
									"textInput": {
										"label": "休暇理由",
										"name": "remark",
										"type": "SINGLE_LINE"
									}
								},
								{
									"dateTimePicker": {
										"label": "开始時間",
										"name": "startTime",
										"type": "DATE_AND_TIME"
									}
								},
								{
									"dateTimePicker": {
										"label": "終了時間",
										"name": "endTime",
										"type": "DATE_AND_TIME"
									}
								}
							]
						}
					]
				}
			}
		},
		"type": "DIALOG"
	}
}`

I use bot-dialogs in Hangouts Chat. Wrapped into json as shown above. 
dateTimePicker is GoogleAppsCardV1DateTimePicker ，but  it cannot be displayed properly.

Thank you very much.

**Comment by diaowenyang** [comment]
![image](https://user-images.githubusercontent.com/18416111/143516792-4036d02d-111a-4066-a562-b164d31c4e26.png)

**Comment by sqrrrl** [comment]
Date picker is not yet supported in Chat dialogs. It's on the roadmap, but I don't have a specific ETA for it at this time. Since this is more of a general help/feature request and not an issue with any of the samples in this repository, I suggest checkout out the resources in the [support guide.](https://developers.google.com/chat/support)
